# Chaos during a stampede

Based on the paper: https://www.sciencedirect.com/science/article/pii/S1569190X20300861?casa_token=eoCj844--UoAAAAA%3AW5IEQVZQbP5ILasesMnahd3iIgfHNXfAWnaI7RsboLHrfqNA-UNxb_pyNF5FIyDN0hoKbjdC-EA 

### To do:
Implement everything

### Ideas:
Implement people as class so that we can define their state and position as parts of that class.

Use code example below, set all bordercells to 500 (= wall)
Use different values for different states of people.
Make custom update rules.

### Steps:
1. Populate board with random amount of people in random positions
2. In each time step, calculate the static floor field Sij, the dynamic floor field Dij and the event floor field Fij with help of the formulas.
3. For each pedestrian, determine his/her state and make a decision regarding movement behavior. If the pedestrian is in
state Ue,Un or Ae, calculate the transition probability according to Eqs. (15)–(17), respectively. If the pedestrian is in state An, he/
she chooses one of the strategies S1, S2 or S3 to evacuate. If the pedestrian is in state C, calculate the probability of him/her
getting up again.
4. Each pedestrian moves to his/her target cell. If the pedestrian chooses a target cell that is occupied by a fallen pedestrian, he/she will be tripped and become a new fallen pedestrian.
5. If the chaos duration is over, uninjured pedestrians regard fallen pedestrians as obstacles and conduct a normal evacuation. There will be no more new fallen pedestrians.
6. When multiple pedestrians choose to move to the same target, one pedestrian is randomly selected with equal probability to move to the target cell, and other pedestrians remain in their original cells.
7. Determine whether the evacuation is over. If there are still uninjured pedestrians in the room, return to step 2 and repeat the simulation process until all the uninjured pedestrians evacuate from the room.

### Variables:

S = static floor: describes pedestrian behavior of finding the shortest path to the exit during the evacuation process.
D = dynamic floor: represents the interactions among pedestrians in the evacuation process.
F = event floor: reflects thhat some pedestrians intend to escape from the stampede location when they are affected by the stampede.
A = risk floor field: depicts that pedestrian movement direction affects the risk of being tripped.

### evac strategies:
S1 = Tries to stay away from the stampede location (Eq 1)
S2 = Follows movement of neighbours 
S3 = keeps moving in same direction until wall is reached, then follows it clockwise or anti clockwise.
     when they stay in the same cell for more then 5 time steps, they change the desired direction randomly.


In [27]:
# imports

import numpy as np
import random
import matplotlib.pyplot as plt

In [39]:
# functions

def init_board(r,N,e,R,state_dic):
    # this function returns 2 things:
    # 1. The board filled with numeric values. Where each state is represented by a certain number
    # 2. The list of people on the board, this is the list that we can iterate over every time.
        # populate board with size r x r with x people
        # decide where exits are with e list of locations of exits
        # set remaining walls to 500

    # create board with all walls being 500
    board = np.ones((r,r)) * 500
    board[1:-1,1:-1] = 0

    # add the exit locations
    for exit_loc in e:
        board[exit_loc[0],exit_loc[1]] = 1

    # calculate all possible locations
    locations = []

    for x in range(1,r-1):
        for y in range(1,r-1):
            locations.append([x,y])

    if len(locations) >= N:
        uniq_locations = random.sample(locations,N)
    else:
        raise ValueError('N can not be greater than the number of free spaces on the board')

    # add the people to the board
    person_list = []

    for i,location in enumerate(uniq_locations):
        # set standard state to 'Un' if exit in range set to 'Ue'
        pstate = 'Un'
        for exit_loc in e:
            if np.sqrt((exit_loc[0]-location[0])**2+(exit_loc[1]-location[1])**2) <= R:
                pstate = 'Ue'
        
        person_list.append(Pedestrian(location,pstate))

        board[location[0], location[1]] = state_dic[pstate]

    return board, person_list 

def calc_S(board, person):
    return S 

def calc_D(board, person):
    return D 

def calc_F(board, person):
    return F 

def calc_tumble(R,ka,kc,board):
    #rho = (sum of num of spaces that are occupied)/abs(U0)
    if rho > 0.64: # more then 4 people/m^2 so trample threshold is exceeded
        eps = 1
    else:
        eps = 0
     
    Aij = np.cos(theta) - 1 # theta is de hoek tussen bewegingsrichting van vorige stap en normaal van huidige cell naar cell ij
    if board[i,j] == 500:
        aij = kc*eps*rho*np.exp(ka*Aij)
    else:
        aij = 1
    
    return aij


def check_state(person):
    
    return state

def move_direction(person,board):
    # this function looks at the current state of the person
    # based on this state it defines it next movement step
    # then it defines the chance of this step being taken
    # if the person tumbles its state is changed to C and the board is adapted
    # next the person gets its new location assigned in person.new_location

    # calc trans prob for every direction, then max trans prob = movement

    if person.state == 'Ue':
        print()
    elif person.state == 'Un':
        print()
    elif person.state == 'Ae':
        print()
    elif person.state == 'An':
        if person.evac_strat == 'S1':
            print()
        elif person.evac_strat == 'S2':
            print() 
        else:
            print()
    elif person.state == 'C':
        print()
        # implement that they get up with probability x
        # where x follows a poisson distribution with lambda = 1 based on the duration that they are down
    else:
        raise ValueError('Non existing person state')

    return location

def check_stampede(people_list):
    states = [person.state for person in people_list]

    if any(not(states == 'left' or states == 'C')):
        stampede = True
    else:
        stampede = False
    
    return stampede

def plot_room(board):
    color_map = {0: np.array([255, 255, 255]), # white
             1: np.array([255, 255, 255]), # white
             2: np.array([0, 255, 0]), # green
             3: np.array([0, 0, 255]), # blue
             4: np.array([255, 0, ]), # red
             5: np.array([255, 153, 51]), # orange
             6: np.array([255, 255, 0]), # yellow
             500: np.array([128, 128, 128])} # gray 

    # make a 3d numpy array that has a color channel dimension   
    data_3d = np.ndarray(shape=(board.shape[0], board.shape[1], 3), dtype=int)
    for i in range(0, board.shape[0]):
        for j in range(0, board.shape[1]):
            data_3d[i][j] = color_map[int(board[i][j])]
    
    return data_3d


# classes

class Pedestrian:
  def __init__(self, location, state):
    self.evac_strat = random.choices(['S1','S2','S3'],(50,30,20))[0]
    self.location = location
    self.state = state 
    self.direction = 'none'
    self.new_location = [0,0]


In [53]:
# parameters
r = 30 # size of board 
N = 100 # number of people
e = [[int(r/2-2),0],[int(r/2-1),0],[int(r/2),0],[int(r/2+1),0]] # exit locations (middle of left wall)

Ts = 1 # occurrence time of the stampede
Tc = Ts + 50 # chaos duration

kc = 0.5 # sensitivity parameter for tumble factor 
ka = 1 # sensitivity parameter for tumble factor 
ks = 5 # sensitivity parameter for the static field
kd = 1 # sensitivity parameter for the dynamic field
alpha = 0.3
delta = 0.3
R = 5 # perception radius for each person

Srange = 8 # stampede range

state_dic = {'Ue':2,'Un':3,'Ae':4,'An':5,'C':6}
# each time step == 0.3s

In [73]:
board, person_list = init_board(r,N,e,R,state_dic) 

Un


In [18]:
# main function

# fill board with people and initialize them

board, person_list = init_board(r,N,e,R,state_dic) 

# add starting board to stampede clip, this will later be transformed to a gif.

stampede_clip = np.zeros((0,r,r,3))
temp = np.reshape(plot_room(board),(1,r,r,3))
stampede_clip = np.vstack((stampede_clip,temp))

time = 1

stampede = True
chaos = False

S = calc_S(board, person)

while stampede:

    if time == Ts:
        chaos = True
        x = random.randint(0,len(person_list))
        person_list[x].state = 'C'
        c_loc = person_list[x].location
        board[c_loc[0],c_loc[1]] = state_dic['C']
        
    
    if time > Tc:
        chaos = False
        # C becomes obstacle (= 500)
        S = calc_S(board)
        # change evacuation strategy of others to normal
        # change to fall = 0

    # step 2: iterate over every person in person_list

    for person in person_list:
        
        # calculate state of person

        person.state = check_state(person)
    
        # calculate Sij, Dij and Fij

        D = calc_D(board, person)
        F = calc_F(board, person)

        # calculate movement of each person 
        # or if person.state = 'C' calculate chance of getting up

        person = move_direction(person,board)
    
    next_locations = [person.new_location for person in person_list if person.state != 'C']

    # find duplicate locations in next_locations list and put in dupes

    dupes = []
    dupes = ...

    if dupes:

        for dupe in dupes:
            # for all dupes calc which person moves and set its location to new location
            # The other persons stay in there original location
        
        for #non dupes:
            # set location to new locations
    
    else:
        for person in person_list:
            person.location = person.new_location

    # check if stampede is over

    stampede = check_stampede(person_list)

    # write current board to total
    temp = np.reshape(plot_room(board),(1,r,r,3))
    stampede_clip = np.vstack((stampede_clip,temp))
    time += 1


[[[0 0 0 1 0 0 0 1 1 0]
  [1 0 0 1 0 0 1 0 0 0]
  [0 1 1 1 1 0 0 0 1 0]
  [0 0 1 1 1 1 0 0 0 0]
  [1 0 0 0 0 1 0 0 0 1]
  [1 0 1 0 1 1 1 0 0 0]
  [1 0 0 1 0 0 0 1 1 0]
  [0 1 1 1 1 1 1 1 1 1]
  [0 0 0 0 0 0 0 1 0 1]
  [0 1 1 1 0 1 0 1 1 0]]]
[[0 0 0 1 0 0 0 1 1 0]
 [1 0 0 1 0 0 1 0 0 0]
 [0 1 1 1 1 0 0 0 1 0]
 [0 0 1 1 1 1 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 1]
 [1 0 1 0 1 1 1 0 0 0]
 [1 0 0 1 0 0 0 1 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 1]
 [0 1 1 1 0 1 0 1 1 0]]
